[project]
name = "projeto-site"
version = "0.1.0"
description = "Projeto site completo com Flask"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "flask>=3.0.3",
    "pandas>=2.2.3",
]
